server:
  port: 9200
spring:
  application:
    name: www.cys.com
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #开启小写后uri也必须小写
          lowerCaseServiceId: true
      routes:
        - id: index
          uri: http://www.cys.com:9200/
          predicates:
            - Path=/
        - id: sso
          uri: lb://sso.cys.com
          predicates:
            - Path=/sso/**
        - id: system
          uri: lb://system.cys.com
          predicates:
            - Path=/system/**
        - id: search
          uri: lb://search.cys.com
          predicates:
            - Path=/search/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug

#jwt:
#  secret:
#    key: asdfghjkl
#  blacklist:
#    key:
#      format=: WT_BLACKLIST::%s